# Generated by Django 4.0.2 on 2022-02-05 19:24

import django.core.validators
from django.db import migrations, models
import petstragram.main.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        max_length=30,
                        validators=[
                            django.core.validators.MinValueValidator(2),
                            petstragram.main.validators.validate_only_letters,
                        ],
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        max_length=30,
                        validators=[
                            django.core.validators.MinValueValidator(2),
                            petstragram.main.validators.validate_only_letters,
                        ],
                    ),
                ),
                ("picture", models.URLField(blank=True, null=True)),
                ("date_of_birth", models.DateTimeField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Do not show", "Do not show"),
                        ],
                        max_length=11,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
