# Generated by Django 4.0.2 on 2022-02-06 00:03

import django.core.validators
from django.db import migrations, models
import petstragram.main.validators


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_pet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="first_name",
            field=models.CharField(
                max_length=30,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    petstragram.main.validators.validate_only_letters,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_name",
            field=models.CharField(
                max_length=30,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    petstragram.main.validators.validate_only_letters,
                ],
            ),
        ),
        migrations.CreateModel(
            name="PetPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(upload_to="")),
                ("description", models.TextField(blank=True, null=True)),
                ("publication_date", models.DateTimeField(auto_now_add=True)),
                ("likes", models.IntegerField(default=0)),
                ("tagged_pets", models.ManyToManyField(to="main.Pet")),
            ],
        ),
    ]
