# Generated by Django 4.0.2 on 2022-02-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_profile_first_name_alter_profile_last_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="petphoto",
            name="photo",
            field=models.ImageField(upload_to="images"),
        ),
    ]
