# Generated by Django 4.0.2 on 2022-02-16 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_petphoto_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
