# Generated by Django 4.0.2 on 2022-04-01 21:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_delete_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="petphoto",
            name="photo",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
    ]
